---
title: "day2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# part 1

```{r}

gravityassist = function(input_df){
  keep_on = TRUE
  pos = 1
  
  while(keep_on == TRUE){
    x = input_df[pos]
    if(x == 1){
      a = input_df[pos + 1]
      b = input_df[pos + 2]
      z = input_df[pos + 3]
      aa = input_df[a + 1]
      bb = input_df[b + 1]
      c = aa + bb
      input_df[z+1] = c
      pos = pos + 4
      x = input_df[pos]
      if(x == 99){
        keep_on = FALSE
        # input_df[pos] = c
        output = input_df
      }
    } else if(x == 2){
      a = input_df[pos + 1]
      b = input_df[pos + 2]
      z = input_df[pos + 3]
      aa = input_df[a + 1]
      bb = input_df[b + 1]
      c = aa * bb
      input_df[z+1] = c
      pos = pos + 4
      x = input_df[pos]
      if(x == 99){
        keep_on = FALSE
        # input_df[pos] = c
        output = input_df
      }
    }
    
  }
  
  return(output)
  
}



```


```{r}

input_df = c(1,0,0,0,99)
input_df = c(2,3,0,3,99)
input_df = c(2,4,4,5,99,0)
input_df = c(1,1,1,4,99,5,6,0,99)
input_df = c(1,9,10,3,2,3,11,0,99,30,40,50)


gravityassist(input_df)[1]
```


```{r}
input_df = c(1,12,2,3,1,1,2,3,1,3,4,3,1,5,0,3,2,1,10,19,1,19,5,23,2,23,9,27,1,5,27,31,1,9,31,35,1,35,10,39,2,13,39,43,1,43,9,47,1,47,9,51,1,6,51,55,1,13,55,59,1,59,13,63,1,13,63,67,1,6,67,71,1,71,13,75,2,10,75,79,1,13,79,83,1,83,10,87,2,9,87,91,1,6,91,95,1,9,95,99,2,99,10,103,1,103,5,107,2,6,107,111,1,111,6,115,1,9,115,119,1,9,119,123,2,10,123,127,1,127,5,131,2,6,131,135,1,135,5,139,1,9,139,143,2,143,13,147,1,9,147,151,1,151,2,155,1,9,155,0,99,2,0,14,0)

gravityassist(input_df)

gravityassist(input_df)[1]
```



# part 2

```{r}

find_op = function(df){
  
  op = df %>% 
    as_vector()
  
  op = op[1]
  
  return(op)
}
```


```{r}
gravityassist = function(input_df){
  input_df = input_df  %>% as_vector()
  keep_on = TRUE
  pos = 1
  
  while(keep_on == TRUE){
    x = input_df[pos]
    if(x == 1){
      a = input_df[pos + 1]
      b = input_df[pos + 2]
      z = input_df[pos + 3]
      aa = input_df[a + 1]
      bb = input_df[b + 1]
      c = aa + bb
      input_df[z+1] = c
      pos = pos + 4
      x = input_df[pos]
      if(x == 99){
        keep_on = FALSE
        # input_df[pos] = c
        output = input_df
      }
    } else if(x == 2){
      a = input_df[pos + 1]
      b = input_df[pos + 2]
      z = input_df[pos + 3]
      aa = input_df[a + 1]
      bb = input_df[b + 1]
      c = aa * bb
      input_df[z+1] = c
      pos = pos + 4
      x = input_df[pos]
      if(x == 99){
        keep_on = FALSE
        # input_df[pos] = c
        output = input_df
      }
    }
    
  }
  output = output %>% as_tibble()
  return(output)
  
}
```


```{r}
sub_inputs = function(x, y){
  input_df[2] = x
  input_df[3] = y
  input_df = input_df %>% 
    enframe(name = NULL)
  return(input_df)
}
```


```{r}

df = enframe(seq(0:99), name = NULL) %>% 
  rename(x = value)

df2 = df %>% 
  rename(y = x)

input_df = c(1,999,999,3,1,1,2,3,1,3,4,3,1,5,0,3,2,1,10,19,1,19,5,23,2,23,9,27,1,5,27,31,1,9,31,35,1,35,10,39,2,13,39,43,1,43,9,47,1,47,9,51,1,6,51,55,1,13,55,59,1,59,13,63,1,13,63,67,1,6,67,71,1,71,13,75,2,10,75,79,1,13,79,83,1,83,10,87,2,9,87,91,1,6,91,95,1,9,95,99,2,99,10,103,1,103,5,107,2,6,107,111,1,111,6,115,1,9,115,119,1,9,119,123,2,10,123,127,1,127,5,131,2,6,131,135,1,135,5,139,1,9,139,143,2,143,13,147,1,9,147,151,1,151,2,155,1,9,155,0,99,2,0,14,0)



df3 = crossing(df,df2) %>% 
  rowwise() %>% 
  mutate(z = map2(x, y, sub_inputs))


df4 = df3 %>% 
  mutate(aa = map(z, gravityassist))

df5 = df4 %>% 
  rowwise() %>% 
  mutate(bb = map_dbl(aa, find_op))

df5 %>% filter(bb == 19690720) %>% 
  mutate(answer = 100 * x + y)

```




